### ISSUE TITLE
Empty Private Repo

### ISSUE THREAD

**Issue by Matthewar** [HPCE/hpce-2017-cw2#43]
My private repo exists but tells me it's an empty repo.
Should I just import from this repo?

**Comment by giuliojiang** [comment]
yes, you'll need to import the code yourself
section 1 of the instructions https://github.com/HPCE/hpce-2017-cw2 tell you how to do it (there's a link for a git quickstart)

**Comment by Matthewar** [comment]
Ah I didn't notice that - I looked at the top of the readme for any details about that, but seeing none immediately, I figured something had gone wrong.
Cheers.
