### ISSUE TITLE
AWS instance does not work with Ubuntu 14.04

### ISSUE THREAD

**Issue by roastedpork** [HPCE/hpce-2017-cw2#45]
My AWS instance with Ubuntu 14.04 was unable to run `sudo apt-get update` (or any other `apt-get` instructions), and it keeps giving 404 not found errors for some of its mirror sites. I have searched through multiple StackOverflow posts but it did not fix the problem. It is likely that 14.04 is not supported anymore, as switching to Ubuntu 16.04 worked perfectly. The `aws.md` guide should be edited to use Ubuntu 16.04 instead.

**Comment by m8pple** [comment]
Sigh. Thanks, and thanks for looking into fixes as well. I'll look at it and update the instructions and later specs. Switching to 16 was on the roadmap anyway, I was just reluctant to change infrastructure.

 I try to test these things over the summer as I can't do it at the start of term, but often things break in the meantime. Recent changes to supported versions of opencl are causing similar problems...
