### ISSUE TITLE
Apply loop transformation without introducing parallelism ?

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw2#46]
Hi,
At the end of Task 7, it mentions "First apply the loop transformation described above, without introducing any parallelism".

However, from the explanation the loop transformation requires us to use "chunks" ( which I would assume refers to the chunks in tbb::parallel_for ).

What does it mean "without introducing any parallelism" ? Are we not expected to use tbb::parallel_for ?

**Comment by m8pple** [comment]
It just suggests that you should do the transformation first using sequential
loops, and only once it works there should you move to parallel loops. You
can go straight to parallel_for if you are confident.

Chunking is a general concept, so you could take this sequential loop:
````
for(int i=0; i<N; i++){
  f(i);
}
````
and chunk it up:
````
for(int i=0; i<N/K; i++){
  for(int k=0; k<K; k++){
    f(i*K+k);
  }
}
````
then move to parallel:
````
parallel_for(0, N/K, [&](int i){
  for(int k=0; k<K; k++){
    f(i*K+k);
  }
});
````
The reason for doing it sequentially first is that it is much easier to debug any problems
with sequential loops. For example, in the code above I'd be inclined to worry about
whether it works for all values of N, and it is much easier to check the logic first in
the sequential version (e.g. if you want to print out values, or use a debugger).
