### ISSUE TITLE
tbb/parallel_for.h: No such file or directory

### ISSUE THREAD

**Issue by bngzl** [HPCE/hpce-2017-cw2#47]
Hi, I'm using MINGW64 on MSYS2 and although this is literally just the first part of assignment 2, I'm having trouble even compiling the first part of the assignment. 

After running make all I receive a fatal error: 
$ make all
g++  -I include -W -Wall -std=c++11 -O3  -c -o src/direct_fourier_transform.o src/direct_fourier_transform.cpp
src/direct_fourier_transform.cpp:6:30: fatal error: tbb/parallel_for.h: No such file or directory

But since we've done CW1, I know that I've installed tbb, and have verified it with pacman -Ss tbb. 
Also, I did try linking the tbb (just in case its a linker error) 

Am I making a careless mistake somewhere? 

Thanks!

**Comment by bngzl** [comment]
The above was attempted on the same MSYS2 I used for CW1 (not the canned version) so I tried attempting it on the canned version... 

This is abit weird but when I tried again on my canned version of MINGW64, it says it cant find my folder of MSYS2... but when I copy and paste the canned version out into my C:\ everything works?? Is this a problem with MINGW64 or is there something I'm missing?

**Comment by m8pple** [comment]
I'm not entirely sure, but this might be something todo with path-length limitations.
When it doesn't work, is the mingw folder placed in a directory with a longer path?

Windows has a limit of 260 characters in the total path, so it is possible that the
combination of the directory containing mingw, plus the path within mingw, plus
the file name, is exceeding the maximum length (?)
