### ISSUE TITLE
gcloud

### ISSUE THREAD

**Issue by filangel** [HPCE/hpce-2017-cw2#48]
Since AWS free tier offers us with a single-core machine, can we use Google Cloud Platform instead, providing 300$ free credit for every Gmail user, enough for even octa-core + GPU machines? I could create installation guide, similar to the one provided for AWS (`aws.md`).

**Comment by m8pple** [comment]
Yes, if you're willing to contribute that it would be great - either send as a pull-request,
or if you put it into the comments as markdown then I can turn it into a file.

I haven't really used GCP (or Azure) much, so have stuck more with the platform that
I use, but more options are better.

The main target platform will still need to be AWS simply to control the assessment
environment, but people may well find it good to have another platform for performance
testing, and also for project work.

**Comment by giuliojiang** [comment]
Computing students could also use the internal cloudstack which is based on Apache CloudStack
