### ISSUE TITLE
sublinear scaling

### ISSUE THREAD

**Issue by prattrip** [HPCE/hpce-2017-cw2#50]
My direct_outer_strong_scaling is showing sub linear scaling. I thought that chunking was supposed to help us avoid sub linear scaling. I am certain I have misunderstood the concept. Is sub linear scaling happening because my computer is also running other operations or is it just the overhead of tbb as you have mentioned?

**Comment by m8pple** [comment]
Chunking is one method that can help us to avoid sub-linear scaling (though not
the only one), but getting true linear strong scaling is really quite difficult. In most
cases you'll see there is still a slow drop-off as you add processors, and if you're
still 3x faster when using 4 processors (i.e. scaling of 0.75) then things are going
reasonably well.

While TBB is pretty well performance optimised, there are still a few truly shared
data-structures (e.g. when a CPU needs to grab a task that another CPU created).
Keeping chunks bigger means that it has to access these data-structures much
less frequently, but there are still other sources of overhead as more CPUs become
active. For example, cache pressure can become more significant - if there is a
cache of size C, then when running with P processors each processor effectively
only gets a cache of size C / P. That means that memory accesses are effectively
becoming slower as more processors are involved.

Clock frequency scaling also may have an effect, as having all the cores active may
lead to thermal throttling.

So while the ideal situation is to get perfect scaling of 1.0, you generally need quite
a big problem relative to the number of CPUs, and to start looking at 2nd order
effects like cache access patterns.
