### ISSUE TITLE
Schrodinger's Factory 

### ISSUE THREAD

**Issue by ia2314** [HPCE/hpce-2017-cw2#54]
When registering the factories I got this output, which I keep getting:

```
$ bin/test_fourier_transform
hpce.direct_fourier_transform
hpce.fast_fourier_transform
hpce.ia2314.direct_fourier_transform_parfor_inner
```

However when I try to time the function, this happens:

```
$ bin/time_fourier_transform hpce.ia2314.direct_fourier_transform_parfor_inner 0 30
Caught exception: No factory registered with the name 'hpce.ia2314.direct_fourier_transform_parfor_inner'
```

Is my factory registered or not?

**Comment by m8pple** [comment]
The first one is using `bin/test_fourier_transform`, while the second is using `bin/time_fourier_transform`.
Have you rebuilt the second executable since you added the new fourier transform?

**Comment by samuknet** [comment]
Had a similar issue, which kept happening to me.

I realised it was just because I was running `make` instead of `make all`.  Running `make all` will ensure that `bin/time_fourier_transform` is also rebuilt.

**Comment by ia2314** [comment]
Thanks a lot!
