### ISSUE TITLE
Tests failing because of C++14

### ISSUE THREAD

**Issue by helicopter88** [HPCE/hpce-2017-cw2#55]
My automated test does not pass because GCC is set to C++11, however I changed my makefile to use C++14, and I would like to use one of the features in C++14.
Can GCC be set to use the C++14 standard?

**Comment by m8pple** [comment]
Yes, that should be fine - I can't see why it would cause anything to break.
I've modified the script, though it won't affect the run that just completed.

What feature are you using, out of interest? Most of the big stuff seems to be coming
in C++17 (from my point of view), so I've so far been sticking to C++11 just for
portability reasons.

**Comment by helicopter88** [comment]
The feature that I use the most is `auto` in lambda arguments, like `[](const auto& chunk){ }`.
