### ISSUE TITLE
Can't push to private repo 

### ISSUE THREAD

**Issue by Afrazinator** [HPCE/hpce-2017-cw2#60]
Hi,

This issue may be due to my novelty with git. The brief git intro specifies that we should pull any changes that were made to the original repo and integrate them with what our directory has on our laptops, then push them to our private repo using `git push private master`. I get this error after pulling everything from the public repo (I believe some changes were made to the readme.md file today). This is my terminal output (including the error that comes from pushing):

<img width="568" alt="screenshot 2017-10-24 17 19 23" src="https://user-images.githubusercontent.com/24629174/31955332-fcac7dde-b8df-11e7-8f33-2f18d3bfafac.png">

Could anyone please help? 

Platform: MAC OS.

**Comment by guigzzz** [comment]
If you do `git log` is your final local commit the same as the latest commit on your private repo online? It would seem that your private repo is ahead of the public repo and your local repo

**Comment by Afrazinator** [comment]
Thanks, I tried that and it asked me to merge, I couldn't find my way out of the merge pop up so I pressed ESC+Shift+zz and then it said merge successful for some reason. I was able to push after that!
