### ISSUE TITLE
Failing tests related to direct_fourier transform_parfor_outer

### ISSUE THREAD

**Issue by DhruvArora96** [HPCE/hpce-2017-cw2#64]
I am failing several tests, related to direct_fourier_transform_parfor_outer.cpp. For example, in my test logs you will see that I am failing test 7 which checks the existence of the file, however it is present in the location. Furthermore I pass test number 29 which checks the file with an external tester. Please advise on the cause of this problem.

**Comment by DhruvArora96** [comment]
On today's test, it has once again failed but the files are present. Is possible to have access to the test script you are running so we can check it ourselves?

**Comment by m8pple** [comment]
Might be related to this issue #67 
So the timestamp is when the results were pushed, not when they were pulled, and
the ones pushed this morning were from yesterday afternoon/evening (I'm not sure when).
