### ISSUE TITLE
Time constraints in manual chunking excercise

### ISSUE THREAD

**Issue by ppp2211** [HPCE/hpce-2017-cw2#65]
In the manual chunking part there's a note: "Time should extend up to 30 seconds per test run"

However, my slowest run (n=4096, K=1) takes just 0.74s. That's way under the recommended max of 30 seconds. I'm doing it on a desktop machine with an i7 at 4.8 GHz, so I have a relatively fast CPU - but 30s vs 0.74s is a 40x difference. To eliminate the machine being at fault, I also checked on a laptop - there it took ~2.5s which is closer, but still off by a factor of over 10.

It seems to scale fine with K, so I don't think there's a problem, but I am slightly confused. Is this expected? (I'm asking mainly because that running each for 30 seconds takes ages to complete, but doesn't seem to be necessary to generate the results.)

**Comment by giuliojiang** [comment]
same here, 30s seems to be a very generous amount of time to collect data for N up to 4096

**Comment by m8pple** [comment]
I think this is similar to the query that came up in issue #56 ?

That said, 30 seconds is not a long time - if you automate them you
can do something else as it runs.

**Comment by ppp2211** [comment]
It is the same, I must've missed that query when browsing issues. That explains it.
