### ISSUE TITLE
Part 7: clarification on whether to use simple_partitioner or auto_partitioner on loop chunks

### ISSUE THREAD

**Issue by Afrazinator** [HPCE/hpce-2017-cw2#69]
Hi, on task 7 it says " Once you have got it working with a non parallel chunked loop, replace the outer loop with a parallel_for loop using simple_partitioner, and check that it still works for different values of HPCE_FFT_LOOP_K. " but on issue #46, a simple parallel_for is incorporated to replace the outer loop without using simple_partitioner. Should we use the simple_partitioner or the auto_partitioner as mentioned in the issue?

**Comment by ppp2211** [comment]
#46 is just pseudocode, you have to use simple_partitioner as otherwise you can't control the chunk sizes (i.e. you cannot create the graphs required for the task).

**Comment by m8pple** [comment]
Yup, as @ppp2211 says, it is just pseudo-code.
