### ISSUE TITLE
Test failing for no obvious reason

### ISSUE THREAD

**Issue by m8pple** [HPCE/hpce-2017-cw2#70]
> I have noticed that one of my tests is failing for coursework 2. I tried investigating the
> problem, but I don't have any printf-s or std::cout's in my code, so I couldn't figure
> out the problem. I also double checked my register factories, makefile and class
> names to no avail.
> 
> I was just wondering if you could shed some light on this error.

![image](https://user-images.githubusercontent.com/3024705/32105135-541b1ab2-bb1f-11e7-9633-f19498a3f0ff.png)

**Comment by m8pple** [comment]
One of the defensive measures used in the tests is that if things take too long, then
they are killed (using `/usr/bin/timeout`). The timeout is set long enough that any
reasonable implementation should complete, but short enough that a few infinite loops
don't cause the entire batch to take a whole day.

I don't think I put any logic in to print a specific message for timeouts, so that's my best guess
for what's happening here. Test 34 should take <10 secs in most case, so the execution
limit is set to 60 seconds. So I'd investigate:
- is the default value of K is actually a good value?
- Are you genuinely skipping ahead? `std::pow` is _very_ expensive compared to a complex
  multiply, so if that is still in the inner loop it will be much slower.

**Comment by vm1414** [comment]
Thank you for the detailed explanation!
